format = """
$cmd_duration\
$shell\
$username\
$sudo\
$character\
"""

right_format = """
$directory\
$git_branch\
$git_status\
$c\
$nodejs\
$python\
$memory_usage\
$aws\
$time\
"""

add_newline = true
command_timeout = 10000

[memory_usage]
format = '$symbol [${ram_pct}]($style)'
disabled = false
threshold = -1
symbol = '󰍛'
style = 'bold dimmed green'

[shell]
fish_indicator = '󰈺'
zsh_indicator = '󰬡'
bash_indicator = ''
style = '#89dceb bold'
disabled = false

[character]
format = "$symbol "
success_symbol = "[◉](bold italic bright-yellow)"
error_symbol = "[⊘](italic purple)"

[sudo]
format = "[$symbol]($style)"
style = "italic #cba6f7"
symbol = "󱃱 "
disabled = false


[username]
style_user = '#f38ba8'
style_root = '#f38ba8 bold'
format = '[$user]($style) '
disabled = false
show_always = true

[directory]
home_symbol = "󰜥 "
truncation_length = 3
truncation_symbol = " "
style = "italic blue"
format = ' [$path]($style)'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
format = '[ $symbol $branch ](fg:#f38ba8)'

[git_status]
format = '[($all_status$ahead_behind )](fg:#f38ba8)'


[cmd_duration]
min_time = 500
format = "[$duration ](italic bright-yellow)"

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "dimmed white"

[nodejs]
format = "[ ($version) ](italic bright-green)"
detect_files = ["package-lock.json", "yarn.lock"]
version_format = "${major}.${minor}"

[python]
format = " py [${symbol}${version} ]($style)"
symbol = "[ ](italic bright-blue)"
version_format = "${major}.${minor}"
style = "italic bright-yellow"

[aws]
format = " aws [$symbol $profile $region]($style)"
style = "italic blue"
symbol = " "

[c]
symbol = " "
format = " c [$symbol($version(-$name))]($style)"
